### ISSUE TITLE
use @mixin or @see instead re generate dockbock per when Accessor update methods

### ISSUE THREAD

**Issue by SocolaDaiCa** [archielite/laravel-facade-docblock-generator#1]
https://github.com/laravel-idea/plugin/issues/520
https://thomasventurini.com/articles/auto-completion-for-laravel-facades/

**Comment by sangnguyenplus** [comment]
Idea is from Laravel facades.
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/6972407/235825840-0b0f6e25-3080-48df-91f7-c542d65baca6.png">

https://github.com/laravel/framework/blob/10.x/src/Illuminate/Support/Facades/DB.php

Not all developers are using Laravel Idea (it's a paid plugin) or Laravel IDE Helper, so that generate doc block is a good way to support all developers.
